/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ColorContrastChecker {
        "language": 'en' | 'de' | 'it' | 'fr';
    }
}
declare global {
    interface HTMLColorContrastCheckerElement extends Components.ColorContrastChecker, HTMLStencilElement {
    }
    var HTMLColorContrastCheckerElement: {
        prototype: HTMLColorContrastCheckerElement;
        new (): HTMLColorContrastCheckerElement;
    };
    interface HTMLElementTagNameMap {
        "color-contrast-checker": HTMLColorContrastCheckerElement;
    }
}
declare namespace LocalJSX {
    interface ColorContrastChecker {
        "language"?: 'en' | 'de' | 'it' | 'fr';
    }
    interface IntrinsicElements {
        "color-contrast-checker": ColorContrastChecker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-contrast-checker": LocalJSX.ColorContrastChecker & JSXBase.HTMLAttributes<HTMLColorContrastCheckerElement>;
        }
    }
}
